=== pierosanttana/ActividadesLMSGI/13_Actividad_DTD_XSD/_01_biblioteca_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="seccion" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="autor" type="xs:string"/>
                                        <xs:element name="anio" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                        <xs:element name="resumen" type="xs:string"/>
                                        <xs:element name="editorial">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="codigo" minOccurs="0" maxOccurs="1"/>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="ciudad" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>

                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>

                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== pierosanttana/ActividadesLMSGI/13_Actividad_DTD_XSD/Actividad13_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "_01_biblioteca_XSD.xsd">
  <nombre>Biblioteca Central</nombre>
  <seccion>
    <libro>
      <titulo>Don Quijote de la Mancha</titulo>
      <autor>Miguel de Cervantes</autor>
      <resumen>Las aventuras de un caballero enloquecido y su fiel escudero.</resumen>
      <editorial>
        <nombre>Ediciones Quixote</nombre>
        <ciudad>Madrid</ciudad>
      </editorial>
    </libro>
    <libro>
      <titulo>Orgullo y prejuicio</titulo>
      <autor>Jane Austen</autor>
      <anio>1813</anio>
      <resumen>La compleja relación entre Elizabeth Bennet y Mr. Darcy en la sociedad inglesa del siglo XIX.</resumen>
      <editorial>
        <nombre>Ediciones Bennet</nombre>
        <ciudad>Londres</ciudad>
      </editorial>
    </libro>
  </seccion>
  <seccion>
    <libro>
      <titulo>La metamorfosis</titulo>
      <autor>Franz Kafka</autor>
      <anio>1915</anio>
      <resumen>La transformación de Gregor Samsa en un insecto y su impacto en la familia.</resumen>
      <editorial>
        <nombre>Ediciones Kafka</nombre>
        <ciudad>Praga</ciudad>
      </editorial>
    </libro>
  </seccion>
  <seccion>
    <libro>
      <titulo>Los miserables</titulo>
      <autor>Victor Hugo</autor>
      <resumen>La historia de Jean Valjean y su redención en la Francia del siglo XIX.</resumen>
      <editorial>
		    <codigo>LM789OP</codigo>
        <nombre>Ediciones Libertad</nombre>
        <ciudad>París</ciudad>
      </editorial>
    </libro>
    <libro>
      <titulo>Moby Dick</titulo>
      <autor>Herman Melville</autor>
      <anio>1851</anio>
      <resumen>La obsesión del capitán Ahab por capturar la ballena blanca.</resumen>
      <editorial>
        <nombre>Ediciones Mar</nombre>
        <ciudad>Nueva York</ciudad>
      </editorial>
    </libro>
  </seccion>
</biblioteca>
