=== pierosanttana/ActividadesLMSGI/13_Actividad_DTD_XSD/_01_empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="NIF" type="xs:string"/>
                <xs:element name="espaniol" type="xs:boolean"/>
                <xs:element name="capital_social">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="euros" type="xs:double"/>
                            <xs:element name="dolares" type="xs:double"/>
                            <xs:element name="yenes" type="xs:double"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="direccion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipo_via" type="xs:string"/>
                            <xs:element name="nombre_via" type="xs:string"/>
                            <xs:element name="CP" type="xs:integer"/>
                            <xs:element name="pais" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado" minOccurs="1" maxOccurs="unbounded">
                               <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" type="xs:string"/>
                                    <xs:element name="apellidos" type="xs:string" minOccurs="2" maxOccurs="unbounded"/>
                                    <xs:element name="DNI" type="xs:string"/>
                                    <xs:element name="extranjero" type="xs:boolean"/>
                                    <xs:element name="fecha_nacimiento" type="xs:date"/>
                                    <xs:element name="salario" type="xs:integer"/>
                                    <xs:element name="direccion" minOccurs="1" maxOccurs="2">
                                        <xs:complexType>
                                            <xs:all>
                                                <xs:element name="direccion_completa" type="xs:string"/>
                                                <xs:element name="pais" type="xs:string"/>
                                            </xs:all>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="casado" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                                </xs:sequence>
                               </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pierosanttana/ActividadesLMSGI/13_Actividad_DTD_XSD/empresa_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>


<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "_01_empresa.xsd">
    <nombre>Nombrea</nombre>
    <NIF>NI556745634</NIF>
    <espaniol>false</espaniol>
    <capital_social>
        <euros>100.50</euros>
    </capital_social>
    <direccion>
        <tipo_via>Tipo de vía</tipo_via>
        <nombre_via>Nombre de la vía</nombre_via>
        <CP>28100</CP>
        <pais>País</pais>
    </direccion>
    <empleados>
        <empleado>
            <nombre>Piero</nombre>
            <apellidos>Santana</apellidos>
            <apellidos>La Rosa</apellidos>
            <DNI>N765356X</DNI>
            <extranjero>false</extranjero>
            <fecha_nacimiento>1993-10-12</fecha_nacimiento>
            <salario>10000</salario>
            <direccion>
                <pais>España</pais>
                <direccion_completa>C\Gran via 67, Madrid</direccion_completa>
            </direccion>
            <casado>true</casado>
        </empleado>
        <empleado>
            <nombre>Piero</nombre>
            <apellidos>Santana</apellidos>
            <apellidos>Santana</apellidos>
            <DNI>N765356X</DNI>
            <extranjero>false</extranjero>
            <fecha_nacimiento>2000-09-10</fecha_nacimiento>
            <salario>10000</salario>
            <direccion>
                <direccion_completa>C\Gran via 67, Madrid</direccion_completa>
                <pais>España</pais>
            </direccion>
            <casado>false</casado>
        </empleado>
        <!-- Puedes añadir más empleados aquí -->
    </empleados>
</empresa>
