<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (nombre,seccion+)>

<!ELEMENT seccion (libro+)>

<!ELEMENT libro (titulo,autor+,anio?,resumen?,editorial)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>

<!ELEMENT editorial (codigo?,nombre,ciudad)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

<!ATTLIST biblioteca codigo CDATA 'B_67' >
<!ATTLIST seccion categoria (Novela | Ciencia_ficción | Aventura | Historia) #REQUIRED>
<!ATTLIST seccion pasillo ID #IMPLIED>
<!ATTLIST libro id ID #REQUIRED>


<!ENTITY tolkien "J.R.R. Tolkien">
]>

<biblioteca codigo="B_67">
  <nombre>Biblioteca nacional</nombre>
  <seccion categoria="Aventura">
    <libro id="L1">
      <titulo>El señor de los anillos</titulo>
      <autor>J.R.R. Tolkien</autor>
      <resumen>Un viaje épico para destruir un anillo mágico.</resumen>
      <editorial>
        <nombre>Editorial Fantástica</nombre>
        <ciudad>Barcelona</ciudad>
      </editorial>
    </libro>
    <libro id="L2">
      <titulo>Harry Potter y la piedra filosofal</titulo>
      <autor> &tolkien; </autor>
      <anio>1997</anio>
      <resumen>Las aventuras de un joven mago en Hogwarts.</resumen>
      <editorial>
        <nombre>Ediciones Mágicas</nombre>
        <ciudad>Londres</ciudad>
      </editorial>
    </libro>
  </seccion>
  <seccion categoria="Novela" pasillo="P3">
    <libro id="L3">
      <titulo>Cien años de soledad</titulo>
      <autor>Gabriel García Márquez</autor>
      <anio>1967</anio>
      <resumen>La historia de la familia Buendía en Macondo.</resumen>
      <editorial>
        <nombre>Ediciones Macondo</nombre>
        <ciudad>Bogotá</ciudad>
      </editorial>
    </libro>
  </seccion>
  <seccion categoria="Ciencia_ficción">
    <libro id="L4">
      <titulo>1984</titulo>
      <autor>George Orwell</autor>
      <resumen>Un futuro distópico donde el pensamiento está controlado.</resumen>
      <editorial>
		    <codigo>ED45TR</codigo>
        <nombre>Editorial Distopía</nombre>
        <ciudad>Londres</ciudad>
      </editorial>
    </libro>
    <libro id="L5">
      <titulo>Fundación</titulo>
      <autor>Isaac Asimov</autor>
      <anio>1951</anio>
      <resumen>La historia de la Fundación para prever el futuro galáctico.</resumen>
      <editorial>
        <nombre>Ediciones Galácticas</nombre>
        <ciudad>Nueva York</ciudad>
      </editorial>
    </libro>
  </seccion>
  <!-- Puedes agregar más secciones y libros según sea necesario -->
</biblioteca>
