=== pierosanttana/ActividadesLMSGI/12_Actividad_XML/_01_DTD_Videojuego.dtd
<!ELEMENT videojuego (nombre,creacion,nota,programadores,compañia,pagina_web)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT creacion EMPTY>
<!ELEMENT nota EMPTY>
<!ELEMENT programadores (programador+)>

<!ELEMENT programador (nombre,primer_apellido,DNI,fecha_nacimiento,direccion)>
<!ELEMENT primer_apellido (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT fecha_nacimiento (dia,mes,anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

<!ELEMENT direccion (tipo_via,nombre_via,codigo_postal,pais)>
<!ELEMENT tipo_via (#PCDATA)>
<!ELEMENT nombre_via (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT compañia (nombre,NIF,direccion)>
<!ELEMENT NIF (#PCDATA)>

<!ELEMENT pagina_web (#PCDATA)>

<!-- Definimos los atributos -->
<!ATTLIST videojuego id ID #REQUIRED>
<!ATTLIST creacion anio CDATA #REQUIRED>
<!ATTLIST nota puntaje CDATA #REQUIRED>
<!ATTLIST programador id ID #REQUIRED>
<!ATTLIST compañia id ID #REQUIRED>

=== pierosanttana/ActividadesLMSGI/12_Actividad_XML/02_Videojuego.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE videojuego SYSTEM "_01_DTD_Videojuego.dtd">

<videojuego id="vj01">
    <nombre>God of War</nombre>
    <creacion anio="1999"/>
    <nota puntaje="8.9"/>
    <programadores>
        <programador id="dev01">
            <nombre>Jack </nombre>
            <primer_apellido>Dorsey</primer_apellido>
            <DNI>95647534X</DNI>
            <fecha_nacimiento>
                <dia>10</dia>
                <mes>12</mes>
                <anio>1985</anio>
            </fecha_nacimiento>
            <direccion>
                <tipo_via>Market Street</tipo_via>
                <nombre_via>Suite 900, San Francisco</nombre_via>
                <codigo_postal>94103</codigo_postal>
                <pais>Estados Unidos</pais>
            </direccion>
        </programador>
        <programador id="dev02">
            <nombre>Evan</nombre>
            <primer_apellido>Williams</primer_apellido>
            <DNI>85487332Y</DNI>
            <fecha_nacimiento>
                <dia>11</dia>
                <mes>12</mes>
                <anio>1974</anio>
            </fecha_nacimiento>
            <direccion>
                <tipo_via>Market Street</tipo_via>
                <nombre_via>Suite 900, San Francisco</nombre_via>
                <codigo_postal>94103</codigo_postal>
                <pais>Estados Unidos</pais>
            </direccion>
        </programador>
    </programadores>
    <compañia id="TWTR">
        <nombre>TWITTER</nombre>
        <NIF>F4536236</NIF>
        <direccion>
            <tipo_via>Calle</tipo_via>
            <nombre_via>Rafael Calvo 18 1 PLANTA</nombre_via>
            <codigo_postal>28010</codigo_postal>
            <pais>España</pais>
        </direccion>
    </compañia>
    <pagina_web>
        <![CDATA[
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        </head>
        <body>
            <div  style="text-align: center;">
            <h1>¡Bienvenido Guerrero, tu destino te espera!</h1>
            <h2 style="color: red;">GOD OF WAR</h2>
            <img src="https://assetsio.reedpopcdn.com/god-of-war-walkthrough-guide-5004-1524154731667.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp" alt="imagen_god_of_war">
            </div>
        </body>
        </html>
        ]]>
    </pagina_web>
</videojuego>
