=== pierosanttana/ActividadesLMSGI/15_Actividad/_01_ciudad_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][a-z]{2,19}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name = "poblacion">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="100"></xs:minInclusive>
                            <xs:maxInclusive value="100000"></xs:maxInclusive>
                        </xs:restriction>
                    </xs:simpleType>

                </xs:element >
                <xs:element name = "alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]{0,9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>    
                            </xs:element>
                            <xs:element name="apellido">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z]+\s[a-zA-Z]+"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>    
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="\+34[1-9]\d{7}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>    
                            </xs:element>
                            <xs:element name="tarjeta_credito" type="xs:integer"></xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="edad">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="18"/>
                                    <xs:maxInclusive value="120"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "funcionarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="funcionario" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreYApellido">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="50"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="codigo_postal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="\d{5}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fecha_nacimiento">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{2}/\d{2}/\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="password">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([A-Z](\d{2})+[%$@!])+"></xs:pattern>
                                                    <xs:minLength value="10"></xs:minLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="cuenta_bancaria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="ES\d{4}\s\d{4}\s\d{4}\s\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[a-zA-Z\d]{1,10}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute name="codigo_identificador">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\D{2}-\d{2,5}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pierosanttana/ActividadesLMSGI/15_Actividad/_01_ciudad_XML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Ciudad codigo_identificador="AA-44" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "_01_ciudad_XSD.xsd">
<nombre>Madris</nombre>
<poblacion>101</poblacion>
<alcalde edad="33">
<nombre>Alcalde</nombre>
<apellido>Apellido Apellido</apellido>
<telefono>+3466556763</telefono>
<tarjeta_credito>6859433475303</tarjeta_credito>
<email>ejemplo@gmail.com</email>
</alcalde>
<funcionarios>
    <funcionario id="funcio2">
        <nombreYApellido>Piero Santana</nombreYApellido>
        <codigo_postal>28100</codigo_postal>
        <fecha_nacimiento>10/12/2000</fecha_nacimiento>
        <password>C13!A34@C12!</password>
        <cuenta_bancaria>ES9933 3339 3332 2220</cuenta_bancaria>
    </funcionario>

    <funcionario id="funcio3">
        <nombreYApellido>Don Santana</nombreYApellido>
        <codigo_postal>28100</codigo_postal>
        <fecha_nacimiento>10/12/2000</fecha_nacimiento>
        <password>C13!A34@C12!</password>
        <cuenta_bancaria>ES9933 3339 3332 2220</cuenta_bancaria>
    </funcionario>

</funcionarios>


</Ciudad>
